### ISSUE TITLE
Materialized views diff exception

### ISSUE THREAD

**Issue by mikolajzieba** [fordfrog/apgdiff#145]
I have tried to compare two identical dump files with one materialized view and received exception:

Exception in thread "main" java.lang.RuntimeException: Cannot find object 'public.view_results_materialized' for statement 'ALTER TABLE public.view_results_materialized OWNER TO admin;'.

Is there any possibility to at least skip materialized views for single diff?

**Comment by rocksfrow** [comment]
@intgr are you currently using materialized views from your own fork? I'd love to get mat. views working and would be willing to fork apgdiff and merge your fix in and use my own fork if I have to

**Comment by DemonVex** [comment]
Fixed by #177
