### ISSUE TITLE
Rename column = data loss

### ISSUE THREAD

**Issue by Jamal-B** [fordfrog/apgdiff#185]
If a column (containing data in our case) is renamed, apgdiff produce this alter command:
```
ALTER TABLE t1
DROP COLUMN col1,
ADD COLUMN new_col1 text;
```

The big problem is that the drop/create method deletes data stored in col1 column, which is not the case with the alter command we really used:
`alter table t1 rename column col1 to new_col1;`

Any solution for this case ?

Thanks.

**Comment by fordfrog** [comment]
apgdiff has no idea whether a column was renamed or one was dropped and another one was created. apgdiff was intended to help with diffing database schemas, its ambition was not to create fully automated tool that would do every possible decision. so it's always good to review the diff before it is applied.

**Comment by Jamal-B** [comment]
Indeed, before posting I knew that "apgdiff has no idea whether a column was renamed" because this information isn't present in the dump file. But I was wondering how it might be possible to use postgresql oid to track renamed columns (I know this information isn't present in the dump too). Thank you for your response and for the great job.
