### ISSUE TITLE
[Feature] CREATE TYPE

### ISSUE THREAD

**Issue by fordfrog** [fordfrog/apgdiff#86]
Converted from [SourceForge issue 2040315](http://sourceforge.net/support/tracker.php?aid=2040315), submitted by jc42

Hi,

Differing types definitions aren't displayed in apgdiff output. As my applications use custom sql types rather massively, it would be useful.

Is this a feature planned in future releases ?

If not, I'm considering to add it on my own, by duplicating the following classes and modifying them:

cz.startnet.utils.pgdiff.PgDiffTables
cz.startnet.utils.pgdiff.parsers.CreateTableParser
cz.startnet.utils.pgdiff.schema.PgTable

It seems the obvious way to do it. Maybe I missed something...

Regards,

JC

**Comment by DemonVex** [comment]
Fixed #144
