### ISSUE TITLE
[Feature] Privileges diff

### ISSUE THREAD

**Issue by fordfrog** [fordfrog/apgdiff#89]
Converted from [SourceForge issue 2948934](http://sourceforge.net/support/tracker.php?aid=2948934), submitted by None

Hello, 

I'd love to see support for GRANT/REVOKE commands.

I have been thinking about implementing this myself for quite some time, but just haven't got around to it yet. Just wanted to see if there are others who would appreciate this functionality. 

Thanks for a great product!

Best regards, 

Marcus Kempe

**Comment by samjgarnham** [comment]
I'd too like this. It would also like CREATE/DROP ROLE support (though not sure how to dump these in the first place).

**Comment by DemonVex** [comment]
Implemented in #129
